---
title: What's in an Education?
author: ~
date: '2020-08-02'
slug: what-s-in-an-education
categories: []
tags: ["Education"]
subtitle: ''
summary: ''
authors: []
lastmod: '2020-08-02T08:28:16-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: true
---

When I was young, my dad always said, “Finish high school, graduate college, get a job, get married, and have kids. I do not care when they happen, but they need to be in that order.” I was fortunate to grow up with 2 happily married parents who both had high school diplomas, college degrees, and launched successful careers. My dad’s words made sense, so I set off to follow my parents’ footsteps.

I finished high school and went on to get degrees in Economics and Applied Mathematics Engineering at Northwestern. As an athlete in college, I spent the summers training to keep my scholarship and compete in national competitions. While this experience taught me valuable lessons in teamwork and leadership, it limited my internship opportunities. Out of college, I did not know what I wanted to do, but I got a job as an Economic Analyst at Abbott. While there I worked with a now close friend named Will Dearden. Will holds a Masters degree from Northwestern in Managerial Economics and Strategy and Undergraduate degrees in Math and Econ from Lehigh. Will and I only overlapped at Abbott for about 3 months, but he introduced me to the fields of Data Science, Machine Learning, and Artificial Intelligence. These fields perfectly combined my passion of automation, mathematics, and economic, so I finally knew how I wanted to launch my career.

## The Ideal Data Scientist

The term “Data Scientist” has seen an [exponential growth in popularity over recent years](https://trends.google.com/trends/explore?date=all&q=data%20science), but what does a Data Scientist mean? And what are the qualifications of the “Ideal Data Scientist”? 

Abbott is a great company that takes care of their employees, but I knew my role was not going to require the technical rigor I wanted for my career, so I started to look for a new job as a Data Scientist. I took online courses to learn R, Python, machine learning, and deep learning. I started attending data science meetups in Chicago to listen to researchers present their latest work and to network with other data scientists. I enjoyed having in-depth conversations about modeling complex AI problems, resolving data issues, and managing the tradeoffs with code deployment. Unfortunately, whenever someone said I should apply to be a data scientist at their company, they asked where I got my PhD.

At this point, I hadn’t even thought about applying for a Master’s Degree. I was only a year out from undergrad, and I knew Northwestern was only starting to adapt their classes to use data science tools, so I didn’t understand why anyone would need a PhD for such a young field. While I felt like the online modules I was taking with DataCamp (before their CEO had his sexual assault scandal) and Coursera were teaching me very relevant theory and job-ready application skills, getting data science interviews without a postgrad degree was difficult, so I applied to Georgia Tech’s Online Masters of Computer Science program (OMSCS).

In 2019, I was accepted to OMSCS around the same time I took a job to consult for Accenture as a Data Scientist. This was thrilling as I knew these were huge steps towards my career goals. As I write this article, I am on my 3rd data science project at Accenture, and I just finished my 3rd OMSCS class. It clear to me now that Artifical Intelligence requires much more than data science. It requires Data Engineers to build out an appropriate Data Warehouse, Machine Learning Engineers to take Data Science models into production ready code, and Network Engineers to manage the deployment of microservices. So while many companies know there is a lot of value in building Artificial Intelligence, most don’t know everything they need to take proof of concept models into production at scale, so companies look for general qualifications in the area of math, economics and computer science. This often means ignoring nanodegree/certificate specializations, and trusting the established college-centric education system.

## Upskilling

In Economics, there is a term called Structural Unemployment, which refers to the level of unemployed people who were displaced by new technologies.  

## College Rigor vs Online Nanodegrees

One of my favorite classes in undergrad was Mechanical Engineering 333: Mechatronics. I loved the class partially because it was my first real introduction to robotics, but also because it had a “flipped” class structure, meaning lectures and quizzes were electronic and done at home, while class time with the professor and TAs was reserved for coding, wiring, and debugging. Recorded lectures allowed everyone to rewatch unclear sections, and the extra face time with the teaching staff helped resolve project struggles much quicker.

Nanodegree programs offer many of the same lecture benefits that flipped classes do, but often do not share the same level of assessment rigor that traditional classes do.

## Modularity is efficiency

One of the best qualities of a good Software Engineer is the ability to write modular code. This means code is written in a way were swapping concepts in and out is quick and easy. Most college curriculum revolves around some sort of quarter/trimester/semester system. While this is likely due to legacy reasons and syncronization across classes/majors, I do not believe this necessarily lines up with how long it takes to learn the fundamentals of any concept. This means I believe the current education (at least for STEM majors), could do with restructuring.

The value of consulting firms comes from its people. In simple terms, consulting is merely the selling of work and the completion of work. This means every external facing employee at the company brings a mix of talent and relationships. Relationships are built 

But what do Bill Gates, Steve Jobs, and Mark Zuckerberg have in common? They are college dropouts.
